#!/usr/bin/env php
<?php
// application.php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/build/UBLSourceCodeGenerator.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommands([new UBLSourceCodeGenerator()]);
// ... register commands

$application->run();