name: PHPUnit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          php_extensions: zip

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        env:
          XDEBUG_MODE: coverage
          TEST_NAME: Scarlett
        with:
          version: 11
          php_version: "8.2"
          php_extensions: xdebug zip
          memory_limit: 256M
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-clover=coverage.xml

      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

